name: media_gram
description: "MediaGram — Premium Micro-Drama Streaming App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  shimmer: ^3.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
